spring:
  application:
    name: bibliokeep-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/bibliokeep
    username: postgres
    password: Inge0925
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

springdoc:
  api-docs:
    enabled: true

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:4z6B8EbGaJpSdTjWnZr4u7x0A9D8GKaPdSgVkYp2s5v8yB_E_H_MbQeThWmZq4}
    expiration-minutes: 15
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:6D5G_KaPdSgVkYp3s6v9y_B_E_H_McQfThWmZq4t7w0z9C8F_JaNdRgUjXn2r5u8}
    expiration-days: 30

logging:
  level:
    org.springframework.security: INFO

