### Enviar archivo a BiblioKeep
POST http://localhost:8080/api/file/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huQGdtYWlsLmNvbSIsInVzZXJJZCI6IjAwNTEzZDgyLTJhZjAtNDJjZi04NmU5LTQwNGUwNmExNDUwOSIsInByZWZlcmVuY2VzIjpbImZpY3Rpb24iLCJoaXN0b3J5Il0sImFubnVhbEdvYWwiOjI0LCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzc2Mzg2MDE1LCJleHAiOjE3NzYzODY5MTV9.vity7Q5EgNp-9YO05YqaW4lvoOrrSApSfyBb6XC97eY
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="imgtest.jpg"
Content-Type: image/jpeg

< ./imgtest.jpg
--WebAppBoundary--